### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by driskerr** [Ugoxya/sql-scratch-capstone-turn-in#1]
## Rubric Score
 
### Criteria 1: Report:
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Every answer has three components: 1) SQL queries, 2) query output as evidence, 3) text interpreting the query results. I wish your conclusions where a little more fleshed out, but overall your interpretation was correct. The design of some slides (there were empty tables on some) could be improved.
 
### Criteria 2: Query Accuracy:
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data as intended.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ You succeed at formatting your queries. Queries adhere to at least 7 rules
of the [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf). 

### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Terms are used correctly throughout the report. You seem to grasp the importance of driving not just visits, but also purchases. Greater explanation of concepts (like first touch, last touch, utm_source vs. utm_campaign) would be appreciated.

 ### Overall Score: 15/16
Your SQL queries are written effectively and pull the correct information. You have a solid sense of how to format SQL queries so that they are readable. Your report provides plenty of supporting evidence for your claims with these well-written queries, but more interpretation and description of the results would be appreciated to demonstrate a high-level understanding of the data.

**Comment by Ugoxya** [comment]
Thanks for the feedback Kerry!

Regards,
Ugonna
